[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tfg-federated-learning"
version = "1.0.0"
description = "Analysis of different federated learning aggregation algorithms"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.24.0",
    "flwr-datasets[vision]>=0.5.0",
    "torch==2.8.0",
    "torchvision==0.23.0",
    "medmnist>=3.0.1",
    "numpy",
    "mlflow"
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "flwrlabs"

[tool.flwr.app.components]
serverapp = "src.server_app:app"
clientapp = "src.client_app:app"

[tool.flwr.app.config]
strategy = "fedavg"
num-server-rounds = 100
fraction-train = 0.75 #change back to 0.75
fraction-evaluate = 1.0
local-epochs = 10
learning-rate = 0.01
batch-size = 128
global-lr = 0                              # Used by SCAFFOLD, overwrite in scaffold.toml
proximal-mu = 0                            # Used by FedProx, overwrite in fedprox.toml
inexact-threshold = 0                      # Used by FedProx, overwrite in fedprox.toml
target-image = ""                          # Used by malicious_server_existing_inference, overwrite in malicious_server_existing_inference.toml
null-image = ""                            # Used by malicious_server_existing_inference overwrite in malicious_server_existing_inference.toml

#######################################################################
# CONFIGURATION MIGRATION NOTICE:
#
# What was previously called "federation config" for SuperLink
# connections in pyproject.toml has been renamed and moved.
#
# These settings are now **SuperLink connection configuration**
# and are defined in the Flower configuration file.
#
# The entries below are commented out intentionally and are kept
# only as a migration reference.
#
# Docs: https://flower.ai/docs/framework/ref-flower-configuration.html
#######################################################################

# [tool.flwr.federations]
# default = "local-simulation"

# [tool.flwr.federations.local-simulation]
# options.num-supernodes = 8
# options.backend.client-resources.num-cpus = 8.0
# options.backend.client-resources.num-gpus = 0.0

# [tool.flwr.federations.local-simulation-gpu]
# options.num-supernodes = 8
# options.backend.client-resources.num-cpus = 4.0
# options.backend.client-resources.num-gpus = 0.0 

# [tool.flwr.federations.supergrid-deployment]
# address = "supergrid.flower.ai"
# enable-account-auth = true
